version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"

  zookeeper:
    image: debezium/zookeeper:0.8
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    kafka:
      image: debezium/kafka:0.8
      ports:
        - 9092:9092
        links:
          - zookeeper
        environment:
          - ZOOKEEPER_CONNECT=zookeeper:2181
      mysql:
        image: debezium/example-mysql:0.8
        ports:
          - 3306:3306
        environment:
          - MYSQL_ROOT_PASSWORD=debezium
          - MYSQL_USER=mysqluser
          - MYSQL_PASSWORD=mysqlpw
      connect:
        image: debezium/connect:0.8
        ports:
          - 8083:8083
        volumes:
          - <REPLACE_THIS_WITH_ABSOLUTE_PATH_TO_MONGODB_CONNECTOR>:/kafka/connect/kafka-connect-mongodb/
        links:
          - kafka
          - mysql
        environment:
          - BOOTSTRAP_SERVERS=kafka:9092
          - GROUP_ID=1
          - CONFIG_STORAGE_TOPIC=my_connect_configs
          - OFFSET_STORAGE_TOPIC=my_connect_offsets
mysql:
  container_name: mysql
  build: /home/vagrant/infra/container/mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=username
    - MYSQL_PASSWORD=password
    - MYSQL_ROOT_PASSWORD=password
  volumes:
    - /home/vagrant/data/maxwell-test/mysql:/var/lib/mysql
    - /home/vagrant/maxwell-test/mysql-config.cnf:/etc/mysql/conf.d/mysql-config.cnf
    - ./install.sql:/docker-entrypoint-initdb.d/install.sql
  restart: always

kafka:
  container_name: kafka
  build: /home/vagrant/infra/container/kafka
  ports:
    - 2181:2181
    - 9092:9092
  environment:
    - ADVERTISED_HOST=192.168.50.4
  restart: always

kafka-manager:
  container_name: kafka-manager
  build: /home/vagrant/infra/container/kafka-manager
  links:
    - kafka
  ports:
    - 9000:9000
  environment:
    - ZK_HOSTS=kafka:2181
    # - APPLICATION_SECRET=password
  restart: always

maxwell:
  container_name: maxwell
  build: /home/vagrant/infra/container/maxwell
  links:
    - mysql
    - kafka
  environment:
    - MYSQL_USER=username
    - MYSQL_PASSWORD=password
    - REPLICATION_USER=maxwell
    - REPLICATION_PASSWORD=password
  restart: always

redis:
  container_name: redis
  build: /home/vagrant/infra/container/redis
  ports:
    - "6379:6379"
  restart: always
